import { Category, Product, PharmacyService, HealthArticle, PharmacySettings } from '../src/types';

export const initialSettings: PharmacySettings = {
  name: 'Gods Favor Pharmacy',
  tagline: 'Trusted Healthcare & Quality Medicines in Kitale',
  locationAddress: 'Along Kijana Wamalwa Road, Kitale Town',
  road: 'Kijana Wamalwa Road',
  town: 'Kitale',
  county: 'Trans Nzoia County',
  country: 'Kenya',
  doctorPhone: '07417758578',
  pochiNumber: '07417758578',
  emergencyNotice: 'For critical medical emergencies, please visit Kitale County Referral Hospital or the nearest emergency department immediately.',
  openingHours: {
    weekdays: '7:30 AM – 9:00 PM',
    saturday: '8:00 AM – 9:00 PM',
    sunday: '9:00 AM – 7:00 PM',
    holidays: '8:30 AM – 6:00 PM',
  },
  email: 'care@godsfavorpharmacy.ke',
  whatsappNumber: '07417758578',
};

export const initialCategories: Category[] = [
  {
    id: 'cat-otc',
    name: 'OTC & Pain Relief',
    slug: 'otc-pain-relief',
    description: 'Over-the-counter pain relief, fever reducers, anti-inflammatory medications.',
    iconName: 'Pill',
    active: true,
    order: 1,
  },
  {
    id: 'cat-prescription',
    name: 'Prescription Medicines',
    slug: 'prescription-medicines',
    description: 'Antibiotics, chronic disease management, cardiovascular, respiratory medicines (requires valid prescription).',
    iconName: 'FileText',
    active: true,
    order: 2,
  },
  {
    id: 'cat-cold-flu',
    name: 'Cold, Flu & Allergy',
    slug: 'cold-flu-allergy',
    description: 'Cough syrups, antihistamines, decongestants, and soothing lozenges.',
    iconName: 'Wind',
    active: true,
    order: 3,
  },
  {
    id: 'cat-baby-mother',
    name: 'Baby & Mother Care',
    slug: 'baby-mother-care',
    description: 'Infant formula, colic relief, pediatric suspensions, maternal supplements, skin care.',
    iconName: 'HeartHandshake',
    active: true,
    order: 4,
  },
  {
    id: 'cat-chronic',
    name: 'Diabetes & Blood Pressure Care',
    slug: 'diabetes-blood-pressure',
    description: 'Blood pressure control, glycemic management, test strips, specialized supplements.',
    iconName: 'Activity',
    active: true,
    order: 5,
  },
  {
    id: 'cat-vitamins',
    name: 'Vitamins & Supplements',
    slug: 'vitamins-supplements',
    description: 'Immunity boosters, multivitamin complexes, calcium, cod liver oil, zinc.',
    iconName: 'Sparkles',
    active: true,
    order: 6,
  },
  {
    id: 'cat-first-aid',
    name: 'First Aid & Wound Care',
    slug: 'first-aid-wound-care',
    description: 'Antiseptics, bandages, gauze, surgical spirits, burn creams, emergency kits.',
    iconName: 'ShieldAlert',
    active: true,
    order: 7,
  },
  {
    id: 'cat-devices',
    name: 'Medical Devices & Equipment',
    slug: 'medical-devices',
    description: 'Digital BP monitors, glucometers, nebulizers, digital thermometers, pulse oximeters.',
    iconName: 'Thermometer',
    active: true,
    order: 8,
  },
];

export const initialProducts: Product[] = [
  // OTC & Pain Relief
  {
    id: 'prod-001',
    categoryId: 'cat-otc',
    name: 'Panadol Extra Tablets (Paracetamol + Caffeine)',
    slug: 'panadol-extra-tablets',
    description: 'Fast and effective relief of tough headaches, backaches, toothaches, joint pain, and fever. Contains paracetamol combined with caffeine for enhanced pain relief.',
    sku: 'OTC-PAN-EXT-20',
    brand: 'GSK',
    price: 180,
    discountPrice: 160,
    stockQuantity: 120,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Tablets',
    activeIngredient: 'Paracetamol 500mg, Caffeine 65mg',
    packSize: 'Pack of 20 Tablets',
    instructions: 'Adults and children 12 years and over: 1 to 2 tablets every 4 to 6 hours as needed. Do not exceed 8 tablets in 24 hours.',
    warnings: 'Do not take with other paracetamol-containing medicines. Consult doctor if symptoms persist after 3 days.',
    storageInfo: 'Store below 30°C in a dry place away from direct sunlight.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-002',
    categoryId: 'cat-otc',
    name: 'Brufen 400mg Tablets (Ibuprofen)',
    slug: 'brufen-400mg-tablets',
    description: 'Non-steroidal anti-inflammatory drug (NSAID) indicated for relief of mild to moderate pain, muscular aches, arthritis pain, dysmenorrhea, and inflammatory conditions.',
    sku: 'OTC-BRU-400-30',
    brand: 'Abbott',
    price: 350,
    stockQuantity: 85,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Film-Coated Tablets',
    activeIngredient: 'Ibuprofen 400mg',
    packSize: 'Pack of 30 Tablets',
    instructions: '1 tablet 3 times daily, preferably after meals with a glass of water.',
    warnings: 'Take with or after food. Avoid if you have active gastric ulcers or severe asthma.',
    storageInfo: 'Store in original container below 25°C.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-003',
    categoryId: 'cat-otc',
    name: 'Gaviscon Double Action Liquid Suspension',
    slug: 'gaviscon-double-action-liquid',
    description: 'Dual-action formulation for rapid, long-lasting relief from heartburn, acid indigestion, and reflux. Forms a protective barrier over stomach contents.',
    sku: 'OTC-GAV-DA-200ML',
    brand: 'Reckitt',
    price: 950,
    discountPrice: 890,
    stockQuantity: 45,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Oral Suspension',
    activeIngredient: 'Sodium Alginate, Sodium Bicarbonate, Calcium Carbonate',
    packSize: '200ml Bottle',
    instructions: 'Adults and children 12 years and over: 10–20ml after meals and at bedtime.',
    warnings: 'Shake well before use. If symptoms do not improve after 7 days, consult a healthcare provider.',
    storageInfo: 'Do not refrigerate. Store below 30°C.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-004',
    categoryId: 'cat-otc',
    name: 'Deep Heat Fast Relief Rub Cream',
    slug: 'deep-heat-fast-relief-rub',
    description: 'Heat therapy rub for soothing relief from muscular aches, stiffness, back strain, rheumatic pain, and sports injuries.',
    sku: 'OTC-DPH-RUB-50G',
    brand: 'Mentholatum',
    price: 450,
    stockQuantity: 60,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-ed200f5e6343?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Topical Cream',
    activeIngredient: 'Menthol 5.91%, Methyl Salicylate 12.80%, Eucalyptus Oil',
    packSize: '50g Tube',
    instructions: 'Gently massage a thin layer into the affected area 2–3 times daily.',
    warnings: 'For external use only. Do not apply to broken or irritated skin. Wash hands after application.',
    storageInfo: 'Store below 25°C. Keep cap tightly closed.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-005',
    categoryId: 'cat-otc',
    name: 'Buscopan 10mg Tablets (Hyoscine Butylbromide)',
    slug: 'buscopan-10mg-tablets',
    description: 'Targeted antispasmodic relief for abdominal cramps, stomach spasms, and irritable bowel syndrome discomfort.',
    sku: 'OTC-BUS-10-20',
    brand: 'Sanofi',
    price: 480,
    stockQuantity: 55,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Coated Tablets',
    activeIngredient: 'Hyoscine Butylbromide 10mg',
    packSize: 'Pack of 20 Tablets',
    instructions: '1 to 2 tablets, 3 times daily with water.',
    warnings: 'Do not use continuously for more than 2 weeks without consulting a doctor.',
    storageInfo: 'Store in dry place below 30°C.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Prescription Medicines
  {
    id: 'prod-006',
    categoryId: 'cat-prescription',
    name: 'Augmentin 625mg Tablets (Amoxicillin/Clavulanate)',
    slug: 'augmentin-625mg-tablets',
    description: 'Broad-spectrum antibiotic combining amoxicillin and clavulanic acid for bacterial infections of respiratory tract, ENT, skin, and urinary tract. Requires pharmacist verification.',
    sku: 'RX-AUG-625-14',
    brand: 'GSK',
    price: 1650,
    stockQuantity: 40,
    prescriptionRequired: true,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Film-Coated Tablets',
    activeIngredient: 'Amoxicillin Trihydrate 500mg, Potassium Clavulanate 125mg',
    packSize: 'Pack of 14 Tablets',
    instructions: '1 tablet every 12 hours at the start of a meal for full prescribed course (usually 5–7 days).',
    warnings: 'PRESCRIPTION REQUIRED. Complete full course as prescribed by doctor. Do not share with others.',
    storageInfo: 'Store in tightly closed foil pack below 25°C.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-007',
    categoryId: 'cat-prescription',
    name: 'Coartem 80/480mg Dispersible & Film Tablets (Artemether-Lumefantrine)',
    slug: 'coartem-adult-tablets',
    description: 'First-line Artemisinin-based Combination Therapy (ACT) for the acute, uncomplicated treatment of Plasmodium falciparum malaria in adults and older children.',
    sku: 'RX-COA-80480-6',
    brand: 'Novartis',
    price: 650,
    stockQuantity: 90,
    prescriptionRequired: true,
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Tablets',
    activeIngredient: 'Artemether 80mg, Lumefantrine 480mg',
    packSize: 'Pack of 6 Tablets (Full 3-Day Adult Course)',
    instructions: 'Complete 3-day course: 1 tablet initially, followed by 5 subsequent doses at specific intervals with food or milk.',
    warnings: 'Take strictly with fatty food or milk to enhance absorption. Complete the full 6-dose schedule.',
    storageInfo: 'Store in blister pack below 30°C.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-008',
    categoryId: 'cat-prescription',
    name: 'Ventolin 100mcg CFC-Free Evohaler (Salbutamol Inhaler)',
    slug: 'ventolin-100mcg-evohaler',
    description: 'Fast-acting bronchodilator for relief of acute bronchospasm in asthma, chronic bronchitis, and exercise-induced asthma.',
    sku: 'RX-VEN-100-200D',
    brand: 'GSK',
    price: 850,
    stockQuantity: 35,
    prescriptionRequired: true,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Metered Dose Inhaler',
    activeIngredient: 'Salbutamol Sulfate 100 micrograms/puff',
    packSize: '200 Actuations (Inhaler)',
    instructions: '1 to 2 puffs for sudden shortness of breath or 15 minutes before exercise.',
    warnings: 'If symptoms persist or require more frequent puffs, seek immediate medical consultation.',
    storageInfo: 'Store below 30°C. Protect from frost and direct sunlight.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-009',
    categoryId: 'cat-prescription',
    name: 'Omeprazole 20mg Delayed-Release Capsules',
    slug: 'omeprazole-20mg-capsules',
    description: 'Proton pump inhibitor (PPI) for treating gastroesophageal reflux disease (GERD), gastric ulcers, and acid-related indigestion.',
    sku: 'RX-OME-20-28',
    brand: 'Dawa Lifesciences',
    price: 420,
    stockQuantity: 110,
    prescriptionRequired: true,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Delayed-Release Capsules',
    activeIngredient: 'Omeprazole 20mg',
    packSize: 'Pack of 28 Capsules',
    instructions: '1 capsule daily in the morning 30–60 minutes before breakfast.',
    warnings: 'Swallow whole with water. Do not crush or chew capsules.',
    storageInfo: 'Store in cool dry place below 25°C.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-010',
    categoryId: 'cat-prescription',
    name: 'Ciprofloxacin 500mg Tablets',
    slug: 'ciprofloxacin-500mg-tablets',
    description: 'Fluoroquinolone antibiotic for bacterial infections including urinary tract, gastrointestinal (typhoid/enteritis), and skin infections.',
    sku: 'RX-CIP-500-10',
    brand: 'Cosmas',
    price: 380,
    stockQuantity: 70,
    prescriptionRequired: true,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Film-Coated Tablets',
    activeIngredient: 'Ciprofloxacin Hydrochloride 500mg',
    packSize: 'Pack of 10 Tablets',
    instructions: '1 tablet twice daily with plenty of water for 5 to 7 days as instructed by doctor.',
    warnings: 'Do not take with dairy products or antacids within 2 hours. Complete full course.',
    storageInfo: 'Store in dry place below 30°C.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Cold, Flu & Allergy
  {
    id: 'prod-011',
    categoryId: 'cat-cold-flu',
    name: 'Fludrex Cold & Flu Multi-Symptom Relief Tablets',
    slug: 'fludrex-cold-flu-tablets',
    description: 'Comprehensive relief from nasal congestion, sore throat, sneezing, headache, fever, and watery eyes associated with common cold and seasonal flu.',
    sku: 'OTC-FLU-MUL-20',
    brand: 'Kuwait Saudi Pharmaceutical',
    price: 320,
    discountPrice: 290,
    stockQuantity: 105,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Tablets',
    activeIngredient: 'Paracetamol 500mg, Pseudoephedrine HCl 30mg, Chlorpheniramine Maleate 2mg',
    packSize: 'Pack of 20 Tablets',
    instructions: 'Adults: 1 tablet every 6–8 hours as needed. Maximum 4 tablets daily.',
    warnings: 'May cause mild drowsiness. Avoid driving or operating machinery if affected.',
    storageInfo: 'Store below 25°C away from moisture.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-012',
    categoryId: 'cat-cold-flu',
    name: 'Cetirizine 10mg Tablets (Allergy Relief)',
    slug: 'cetirizine-10mg-tablets',
    description: 'Non-drowsy 24-hour antihistamine for allergic rhinitis, hay fever, itchy eyes, runny nose, and allergic skin hives.',
    sku: 'OTC-CET-10-30',
    brand: 'Regal Pharmaceuticals',
    price: 250,
    stockQuantity: 130,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Film-Coated Tablets',
    activeIngredient: 'Cetirizine Hydrochloride 10mg',
    packSize: 'Pack of 30 Tablets',
    instructions: '1 tablet once daily in the evening with a glass of water.',
    warnings: 'Consult your doctor if pregnant or breastfeeding before use.',
    storageInfo: 'Store in original packaging below 30°C.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-013',
    categoryId: 'cat-cold-flu',
    name: 'Benylin 4-Flu Cough & Congestion Syrup',
    slug: 'benylin-4-flu-syrup',
    description: 'Complete 4-in-1 formula tackling productive cough, nasal congestion, runny nose, and body fever.',
    sku: 'OTC-BEN-4FLU-100ML',
    brand: 'Johnson & Johnson',
    price: 680,
    stockQuantity: 48,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Syrup',
    activeIngredient: 'Diphenhydramine, Pseudoephedrine, Paracetamol',
    packSize: '100ml Bottle',
    instructions: 'Adults: 10ml to 20ml every 4 to 6 hours as needed.',
    warnings: 'Not recommended for children under 12 without pediatric consultation.',
    storageInfo: 'Store below 25°C. Keep out of reach of children.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-014',
    categoryId: 'cat-cold-flu',
    name: 'Otrivin 0.1% Adult Nasal Spray (Xylometazoline)',
    slug: 'otrivin-adult-nasal-spray',
    description: 'Fast-acting nasal decongestant relieving blocked nose, sinusitis pressure, and rhinitis within 2 minutes for up to 10 hours.',
    sku: 'OTC-OTR-AD-10ML',
    brand: 'Haleon',
    price: 520,
    stockQuantity: 42,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-ed200f5e6343?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Nasal Spray',
    activeIngredient: 'Xylometazoline Hydrochloride 0.1%',
    packSize: '10ml Metered Spray',
    instructions: '1 spray into each nostril 2–3 times daily as needed.',
    warnings: 'Do not use for more than 5 consecutive days to prevent rebound nasal congestion.',
    storageInfo: 'Store below 30°C.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-015',
    categoryId: 'cat-cold-flu',
    name: 'Strepsils Honey & Lemon Lozenges',
    slug: 'strepsils-honey-lemon',
    description: 'Dual antibacterial action soothing sore throat discomfort, dryness, and throat tickles with natural honey and lemon flavor.',
    sku: 'OTC-STR-HL-24',
    brand: 'Reckitt',
    price: 360,
    stockQuantity: 80,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Lozenges',
    activeIngredient: '2,4-Dichlorobenzyl Alcohol 1.2mg, Amylmetacresol 0.6mg',
    packSize: 'Pack of 24 Lozenges',
    instructions: 'Dissolve 1 lozenge slowly in mouth every 2 to 3 hours as needed.',
    warnings: 'Not suitable for young children who may choke on hard lozenges.',
    storageInfo: 'Store below 25°C in dry conditions.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Baby & Mother Care
  {
    id: 'prod-016',
    categoryId: 'cat-baby-mother',
    name: 'Infacol Wind & Infant Colic Oral Drops',
    slug: 'infacol-infant-colic-drops',
    description: 'Clinically proven relief for infant colic, griping pains, and trapped wind from birth onwards. Gentle simethicone formulation with built-in dropper pipette.',
    sku: 'OTC-INF-COL-50ML',
    brand: 'Teva',
    price: 1100,
    discountPrice: 990,
    stockQuantity: 30,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Oral Drops',
    activeIngredient: 'Simethicone 40mg/ml',
    packSize: '50ml Bottle with Dropper',
    instructions: 'One full dropper (0.5ml) administered before each baby feed.',
    warnings: 'Suitable from newborn age. Do not exceed recommended dosage.',
    storageInfo: 'Store below 25°C. Do not freeze.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-017',
    categoryId: 'cat-baby-mother',
    name: 'Calpol Infant Suspension (Paracetamol 120mg/5ml)',
    slug: 'calpol-infant-suspension',
    description: 'Sugar-free strawberry-flavored paracetamol suspension for soothing infant fever, teething pain, sore throat, and post-immunization discomfort.',
    sku: 'OTC-CAL-INF-100ML',
    brand: 'Johnson & Johnson',
    price: 620,
    stockQuantity: 50,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Oral Suspension',
    activeIngredient: 'Paracetamol 120mg per 5ml',
    packSize: '100ml Bottle with Syringe',
    instructions: 'Use the measuring syringe provided according to the child weight/age chart on carton.',
    warnings: 'Leave at least 4 hours between doses. Do not give more than 4 doses in 24 hours.',
    storageInfo: 'Store below 25°C. Do not freeze.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-018',
    categoryId: 'cat-baby-mother',
    name: 'Pregnacare Plus Dual Pack (Maternal Multivitamins + Omega-3 DHA)',
    slug: 'pregnacare-plus-tablets',
    description: 'Expert comprehensive nutritional support during pregnancy containing 400mcg folic acid, essential iron, calcium, and high-purity Omega-3 DHA capsules for fetal brain and eye development.',
    sku: 'OTC-PREG-PLS-56',
    brand: 'Vitabiotics',
    price: 2400,
    discountPrice: 2250,
    stockQuantity: 25,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Tablets & Softgel Capsules',
    activeIngredient: 'Folic Acid 400mcg, Iron 17mg, Zinc 15mg, DHA 300mg, EPA 60mg',
    packSize: 'Dual Pack (28 Multivitamin Tablets + 28 Omega-3 Capsules)',
    instructions: '1 multivitamin tablet PLUS 1 omega-3 capsule daily with main meal and cold water.',
    warnings: 'Do not take on an empty stomach. Not a substitute for a balanced diet.',
    storageInfo: 'Store below 25°C in a cool dry place.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-019',
    categoryId: 'cat-baby-mother',
    name: 'Sudocrem Antiseptic Healing Nappy Rash Cream',
    slug: 'sudocrem-healing-cream-125g',
    description: 'Clinically proven to soothe, heal and protect delicate infant skin from diaper rash, eczema, bedsores, and minor burns.',
    sku: 'OTC-SUD-CRM-125G',
    brand: 'Teva',
    price: 850,
    stockQuantity: 40,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Topical Healing Cream',
    activeIngredient: 'Zinc Oxide 15.25%, Benzyl Benzoate 1.01%, Benzyl Cinnamate 0.15%',
    packSize: '125g Tub',
    instructions: 'Apply a thin layer to clean, dry skin at every nappy change.',
    warnings: 'For external use only. Keep out of eyes.',
    storageInfo: 'Store below 25°C.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-020',
    categoryId: 'cat-baby-mother',
    name: 'ORS Electrolytes + Zinc Pediatric Sachets',
    slug: 'ors-zinc-pediatric-sachets',
    description: 'WHO-recommended oral rehydration salts formulation with Zinc Sulfate to restore fluids, vital electrolytes, and accelerate recovery from pediatric diarrhea and dehydration.',
    sku: 'OTC-ORS-ZNC-5S',
    brand: 'Universal Corporation',
    price: 150,
    stockQuantity: 150,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Oral Powder Sachets + Dispersible Zinc',
    activeIngredient: 'Sodium Chloride, Potassium Chloride, Trisodium Citrate, Glucose, Zinc Sulfate 20mg',
    packSize: 'Pack of 5 Rehydration Sachets + Zinc Tablets',
    instructions: 'Dissolve 1 sachet in exactly 500ml of clean drinking water. Administer after every loose stool.',
    warnings: 'Use prepared solution within 24 hours. Do not boil prepared solution.',
    storageInfo: 'Store in dry place below 30°C.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Diabetes & Blood Pressure Care
  {
    id: 'prod-021',
    categoryId: 'cat-chronic',
    name: 'Amlodipine 5mg Tablets (Blood Pressure Management)',
    slug: 'amlodipine-5mg-tablets',
    description: 'Calcium channel blocker prescribed for hypertension (high blood pressure) and prevention of chronic stable angina.',
    sku: 'RX-AML-5-30',
    brand: 'Dawa Pharmaceuticals',
    price: 350,
    stockQuantity: 80,
    prescriptionRequired: true,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Tablets',
    activeIngredient: 'Amlodipine Besylate 5mg',
    packSize: 'Pack of 30 Tablets (1 Month Supply)',
    instructions: 'Take 1 tablet once daily at the same time each day with or without food.',
    warnings: 'PRESCRIPTION REQUIRED. Do not discontinue without medical supervision.',
    storageInfo: 'Store below 25°C protected from light and moisture.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-022',
    categoryId: 'cat-chronic',
    name: 'Glucophage 500mg Tablets (Metformin Hydrochloride)',
    slug: 'glucophage-500mg-tablets',
    description: 'Oral biguanide antidiabetic medication for glycemic control in Type 2 Diabetes Mellitus, helping reduce insulin resistance.',
    sku: 'RX-GLU-500-100',
    brand: 'Merck Healthcare',
    price: 850,
    stockQuantity: 65,
    prescriptionRequired: true,
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Film-Coated Tablets',
    activeIngredient: 'Metformin Hydrochloride 500mg',
    packSize: 'Pack of 100 Tablets',
    instructions: '1 tablet 2 to 3 times daily with or immediately after meals.',
    warnings: 'PRESCRIPTION REQUIRED. Regular blood glucose monitoring recommended.',
    storageInfo: 'Store in original packaging below 30°C.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-023',
    categoryId: 'cat-chronic',
    name: 'Losartan Potassium 50mg Tablets',
    slug: 'losartan-50mg-tablets',
    description: 'Angiotensin II receptor blocker (ARB) used in treatment of high blood pressure and renal protection in diabetic hypertensive patients.',
    sku: 'RX-LOS-50-30',
    brand: 'Elys Chemical Industries',
    price: 450,
    stockQuantity: 75,
    prescriptionRequired: true,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Film-Coated Tablets',
    activeIngredient: 'Losartan Potassium 50mg',
    packSize: 'Pack of 30 Tablets',
    instructions: '1 tablet once daily with water.',
    warnings: 'PRESCRIPTION REQUIRED. Contraindicated during pregnancy.',
    storageInfo: 'Store in dry place below 30°C.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-024',
    categoryId: 'cat-chronic',
    name: 'Accu-Chek Instant Blood Glucose Test Strips (50 Strips)',
    slug: 'accu-chek-instant-test-strips-50',
    description: 'High-accuracy blood glucose test strips for Accu-Chek Instant meters. Requires small 0.6µL blood sample with results in under 4 seconds.',
    sku: 'DEV-ACC-STR-50',
    brand: 'Roche Diagnostics',
    price: 2300,
    discountPrice: 2150,
    stockQuantity: 40,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Diagnostic Test Strips',
    activeIngredient: 'FAD-Glucose Dehydrogenase Enzyme',
    packSize: 'Vial of 50 Test Strips',
    instructions: 'Insert strip into meter, apply small capillary blood sample to yellow edge.',
    warnings: 'Close vial cap tightly immediately after removing a strip. Do not use expired strips.',
    storageInfo: 'Store between 4°C and 30°C. Do not freeze.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Vitamins & Supplements
  {
    id: 'prod-025',
    categoryId: 'cat-vitamins',
    name: 'Neurobion Forte Vitamin B-Complex Tablets',
    slug: 'neurobion-forte-tablets',
    description: 'High-potency neurotropic B-vitamins (B1, B6, B12) formulated for nerve health, peripheral neuropathy relief, numbness, tingling sensations, and energy regeneration.',
    sku: 'OTC-NEU-FRT-30',
    brand: 'P&G Health',
    price: 650,
    stockQuantity: 95,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Sugar-Coated Tablets',
    activeIngredient: 'Thiamine (B1) 100mg, Pyridoxine (B6) 200mg, Cyanocobalamin (B12) 200mcg',
    packSize: 'Pack of 30 Tablets',
    instructions: '1 tablet 1 to 3 times daily with meals, or as directed by a healthcare professional.',
    warnings: 'Do not exceed stated dose without physician advice.',
    storageInfo: 'Store below 25°C protected from light.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-026',
    categoryId: 'cat-vitamins',
    name: 'Seven Seas Pure Cod Liver Oil Plus Vitamin D Syrup',
    slug: 'seven-seas-cod-liver-oil-syrup',
    description: 'Traditional rich source of natural Omega-3 fatty acids EPA & DHA, Vitamin A, and Vitamin D for healthy bones, teeth, immunity, and brain function.',
    sku: 'OTC-SEV-CLO-300ML',
    brand: 'Seven Seas / P&G',
    price: 1350,
    stockQuantity: 38,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Oral Liquid Oil',
    activeIngredient: 'Purified Cod Liver Oil, Vitamin A, Vitamin D3',
    packSize: '300ml Glass Bottle',
    instructions: 'Children 1–5 years: 5ml daily. Adults and children over 5: 10ml daily.',
    warnings: 'Contains fish products. Consult doctor if on blood thinning medication.',
    storageInfo: 'Store in cool place. Refrigerate after opening and use within 2 months.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-027',
    categoryId: 'cat-vitamins',
    name: 'Redoxon Triple Action Effervescent Vitamin C 1000mg + D + Zinc',
    slug: 'redoxon-triple-action-effervescent',
    description: 'Triple-action immunity defense formula combining high-strength Vitamin C (1000mg), Vitamin D (400IU), and Zinc (10mg) in delicious effervescent orange flavor.',
    sku: 'OTC-RED-TRP-15',
    brand: 'Bayer Healthcare',
    price: 950,
    discountPrice: 880,
    stockQuantity: 65,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-ed200f5e6343?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Effervescent Tablets',
    activeIngredient: 'Ascorbic Acid (Vit C) 1000mg, Zinc 10mg, Vitamin D 400IU',
    packSize: 'Tube of 15 Effervescent Tablets',
    instructions: 'Dissolve 1 tablet completely in a glass of water (200ml) and drink once daily.',
    warnings: 'Do not swallow tablet whole. Not suitable for individuals with kidney stones.',
    storageInfo: 'Keep tube tightly closed in dry location below 25°C.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-028',
    categoryId: 'cat-vitamins',
    name: 'Wellman 50+ / Original Comprehensive Multivitamin',
    slug: 'wellman-multivitamin-tablets',
    description: 'Advanced 29-nutrient bio-active formula specifically tailored to maintain optimal vitality, cardiovascular wellness, energy release, and immune health for men.',
    sku: 'OTC-WEL-MAN-30',
    brand: 'Vitabiotics',
    price: 1850,
    stockQuantity: 30,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Micro-Nutrient Tablets',
    activeIngredient: 'Co-Q10, L-Carnitine, Siberian Ginseng, Zinc, B-Complex, Bioflavonoids',
    packSize: 'Pack of 30 Tablets',
    instructions: '1 tablet daily with your main meal. Swallow with water.',
    warnings: 'Take with food. Do not chew.',
    storageInfo: 'Store below 25°C in a dry place.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // First Aid & Wound Care
  {
    id: 'prod-029',
    categoryId: 'cat-first-aid',
    name: 'Savlon Antiseptic Liquid Disinfectant 500ml',
    slug: 'savlon-antiseptic-liquid-500ml',
    description: 'Trusted broad-spectrum antiseptic solution for cleansing cuts, grazes, insect bites, minor burns, personal hygiene, and antiseptic wound irrigation.',
    sku: 'FA-SAV-LIQ-500ML',
    brand: 'Johnson & Johnson',
    price: 480,
    stockQuantity: 70,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Antiseptic Solution',
    activeIngredient: 'Chlorhexidine Gluconate 0.3% w/v, Cetrimide 3.0% w/v',
    packSize: '500ml Bottle',
    instructions: 'Dilute 1 part Savlon with 20 parts clean water for wound washing.',
    warnings: 'For external use only. Do not ingest. Keep out of reach of children.',
    storageInfo: 'Store below 30°C.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-030',
    categoryId: 'cat-first-aid',
    name: 'Betadine 10% Antiseptic Ointment (Povidone-Iodine)',
    slug: 'betadine-antiseptic-ointment-20g',
    description: 'Gold-standard microbicidal ointment targeting bacteria, fungi, and protozoa for treatment and prevention of infection in minor wounds, burns, and cuts.',
    sku: 'FA-BET-OIN-20G',
    brand: 'Mundipharma',
    price: 380,
    stockQuantity: 85,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-ed200f5e6343?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Topical Ointment',
    activeIngredient: 'Povidone-Iodine 10% w/w',
    packSize: '20g Tube',
    instructions: 'Clean affected area and apply directly 1 to 2 times daily. May be covered with dressing.',
    warnings: 'Do not use if allergic to iodine. For external use only.',
    storageInfo: 'Store below 25°C.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-031',
    categoryId: 'cat-first-aid',
    name: 'Comprehensive Home & Vehicle First Aid Kit (45 Pieces)',
    slug: 'comprehensive-first-aid-kit-45pc',
    description: 'Complete emergency first aid response kit containing sterile gauze pads, adhesive bandages, elastic crepe bandage, surgical tape, scissors, tweezers, antiseptic wipes, burn dressing, and safety pins in a durable zipped case.',
    sku: 'FA-KIT-45PC-BOX',
    brand: 'MedKit Pro',
    price: 2200,
    discountPrice: 1950,
    stockQuantity: 28,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Emergency Medical Kit',
    activeIngredient: 'Sterile First Aid Equipment & Bandages',
    packSize: '45-Piece Red Waterproof Case',
    instructions: 'Refer to enclosed quick first aid guidance manual during emergencies.',
    warnings: 'Inspect contents periodically and replenish used supplies.',
    storageInfo: 'Store in an easily accessible, dry location.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // Medical Devices & Equipment
  {
    id: 'prod-032',
    categoryId: 'cat-devices',
    name: 'Omron M2 Basic Automatic Digital Upper Arm Blood Pressure Monitor',
    slug: 'omron-m2-digital-bp-monitor',
    description: 'Clinically validated upper arm blood pressure monitor featuring Intellisense technology for comfortable, accurate, and rapid systolic, diastolic, and pulse rate readings with irregular heartbeat detection.',
    sku: 'DEV-OMR-M2-BOX',
    brand: 'Omron Healthcare',
    price: 5200,
    discountPrice: 4850,
    stockQuantity: 20,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Digital Medical Diagnostic Device',
    activeIngredient: 'Oscillometric Pressure Sensor',
    packSize: 'Complete Unit (Monitor + Medium Cuff 22–32cm + 4 AA Batteries + Case)',
    instructions: 'Sit comfortably with arm supported at heart level. Press Start button for one-touch automated measurement.',
    warnings: 'Do not measure immediately after exercise, caffeine, or smoking.',
    storageInfo: 'Store in protective case in dry conditions.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-033',
    categoryId: 'cat-devices',
    name: 'Accu-Chek Instant Blood Glucose Monitoring Starter Kit',
    slug: 'accu-chek-instant-starter-kit',
    description: 'Complete blood glucose test system including modern Instant glucometer, Softclix lancing pen, 10 sterile lancets, 10 test strips, and carry case. Features wireless sync capability.',
    sku: 'DEV-ACC-KIT-ST',
    brand: 'Roche Diagnostics',
    price: 3400,
    discountPrice: 3100,
    stockQuantity: 22,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Blood Glucose Testing Kit',
    activeIngredient: 'Electrochemical Biosensor System',
    packSize: 'Full Starter Kit Box',
    instructions: 'Wash hands, insert strip, lance fingertip, apply blood drop to strip. Read result in 4 seconds.',
    warnings: 'Use single-use lancets once only and dispose safely in a sharps container.',
    storageInfo: 'Store between 4°C and 30°C.',
    isFeatured: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-034',
    categoryId: 'cat-devices',
    name: 'Fingertip Pulse Oximeter OLED (SpO2 & Pulse Rate Monitor)',
    slug: 'fingertip-pulse-oximeter-oled',
    description: 'Non-invasive handheld pulse oximeter displaying accurate blood oxygen saturation (SpO2), heart pulse rate, and plethysmograph waveform on a bright dual-color OLED screen.',
    sku: 'DEV-OXI-FNG-OLED',
    brand: 'ChoiceMMed',
    price: 1650,
    stockQuantity: 35,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Optical Biosensor Diagnostic Device',
    activeIngredient: 'Dual-Wavelength Photodiode Sensor',
    packSize: '1 Unit + Lanyard + 2 AAA Batteries',
    instructions: 'Insert clean dry finger into rubber chamber, press power button, keep still during measurement.',
    warnings: 'Nail polish or cold fingers may affect reading accuracy.',
    storageInfo: 'Store in dry place at room temperature.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-035',
    categoryId: 'cat-devices',
    name: 'Digital Waterproof Oral & Axillary Clinical Thermometer',
    slug: 'digital-clinical-thermometer',
    description: 'Fast 10-second digital thermometer with high fever alert beep, memory recall, and flexible waterproof probe for oral, rectal, or underarm temperature checks.',
    sku: 'DEV-THM-DIG-FLEX',
    brand: 'Beurer Medical',
    price: 450,
    stockQuantity: 75,
    prescriptionRequired: false,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=800&auto=format&fit=crop&q=80',
    active: true,
    dosageForm: 'Electronic Diagnostic Thermometer',
    activeIngredient: 'Precision Thermistor Sensor',
    packSize: '1 Thermometer in Protective Clear Case',
    instructions: 'Place under tongue or armpit until the confirmation beep sounds (approx 10–30 seconds).',
    warnings: 'Disinfect probe with alcohol swab before and after each use.',
    storageInfo: 'Store in clear plastic case below 40°C.',
    isFeatured: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const initialServices: PharmacyService[] = [
  {
    id: 'srv-001',
    name: 'Prescription Dispensing & Review',
    slug: 'prescription-dispensing',
    shortDescription: 'Professional dispensing of doctor prescriptions with comprehensive drug interaction checks and patient counseling.',
    fullDescription: 'Our certified pharmacy practitioners thoroughly verify all written and digital prescriptions, check for potential drug interactions or contraindications, and provide tailored dosage guidance to ensure optimal therapeutic outcomes.',
    priceEstimate: 'Free consultation with medicine purchase',
    duration: '10–15 mins',
    iconName: 'FileText',
    category: 'Clinical Dispensing',
    available: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'srv-002',
    name: 'Doctor & Pharmacist Consultations',
    slug: 'doctor-pharmacist-consultation',
    shortDescription: 'Direct medical guidance, medication reviews, and health advice with our pharmacy practitioner.',
    fullDescription: 'Speak directly with our qualified pharmacy doctor and clinical staff via phone (07417758578), WhatsApp, or in-person at our Kitale clinic. Get expert guidance on minor ailments, symptom management, and when to seek specialized hospital referral.',
    priceEstimate: 'KSh 200 / Free on call: 07417758578',
    duration: '15–20 mins',
    iconName: 'PhoneCall',
    category: 'Consultations',
    available: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'srv-003',
    name: 'Blood Pressure Screening & Monitoring',
    slug: 'blood-pressure-screening',
    shortDescription: 'Accurate clinical BP check, hypertension risk assessment, and personalized lifestyle counseling.',
    fullDescription: 'Hypertension is often silent. Drop by our Kijana Wamalwa Road branch for an immediate, high-precision blood pressure screening. We log your historic readings and counsel you on dietary, physical, and medication adjustments.',
    priceEstimate: 'KSh 100',
    duration: '5–10 mins',
    iconName: 'Activity',
    category: 'Diagnostic Screening',
    available: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'srv-004',
    name: 'Random Blood Sugar (Glucose) Testing',
    slug: 'blood-sugar-testing',
    shortDescription: 'Instant finger-prick glucose check for diabetes screening and chronic glycemic monitoring.',
    fullDescription: 'Get your blood glucose levels checked in under 10 seconds using clinically calibrated biosensors. Ideal for diabetic patients monitoring their glycemic control or routine wellness screening.',
    priceEstimate: 'KSh 150',
    duration: '5 mins',
    iconName: 'HeartPulse',
    category: 'Diagnostic Screening',
    available: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'srv-005',
    name: 'Vaccinations & Immunizations',
    slug: 'vaccinations-immunizations',
    shortDescription: 'Routine adult and pediatric vaccines administered by qualified healthcare professionals.',
    fullDescription: 'We provide safe, temperature-controlled vaccine administration including Flu (Influenza), Tetanus Toxoid, Hepatitis B, Typhoid, and pediatric catch-up vaccines in a clean clinical environment.',
    priceEstimate: 'From KSh 500 (varies by vaccine)',
    duration: '15 mins',
    iconName: 'ShieldCheck',
    category: 'Preventive Care',
    available: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'srv-006',
    name: 'Mother & Baby Health Clinic',
    slug: 'mother-baby-care',
    shortDescription: 'Infant growth tracking, maternal health guidance, weaning advice, and pediatric support.',
    fullDescription: 'Dedicated maternal and pediatric pharmacy support: baby weight monitoring, colic management guidance, maternal prenatal & postnatal nutrition, and safe pediatric medication dosing.',
    priceEstimate: 'Free with service appointment',
    duration: '20 mins',
    iconName: 'HeartHandshake',
    category: 'Family Healthcare',
    available: true,
    featured: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'srv-007',
    name: 'First Aid & Wound Dressing',
    slug: 'first-aid-wound-dressing',
    shortDescription: 'Aseptic wound cleansing, minor burn dressing, bandage application, and suture care.',
    fullDescription: 'Prompt clinical dressing for minor cuts, road abrasions, domestic burns, and post-surgical wound maintenance using sterile antiseptics and modern non-adherent dressings.',
    priceEstimate: 'From KSh 300',
    duration: '15–30 mins',
    iconName: 'Bandage',
    category: 'Emergency & First Aid',
    available: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'srv-008',
    name: 'Chronic Disease Refill & Management',
    slug: 'chronic-disease-management',
    shortDescription: 'Structured monthly medication refills and adherence support for Hypertension, Diabetes, and Asthma.',
    fullDescription: 'Never miss a dose of vital chronic medicines. We coordinate recurring refills, remind you ahead of time, check for side effects, and coordinate with your primary physician.',
    priceEstimate: 'Free refill coordination',
    duration: '10 mins',
    iconName: 'CalendarCheck',
    category: 'Chronic Care',
    available: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'srv-009',
    name: 'Family Planning & Reproductive Health',
    slug: 'family-planning-reproductive-health',
    shortDescription: 'Confidential reproductive health counseling, contraceptive guidance, and maternal supplies.',
    fullDescription: 'Private, respectful consultation on modern contraceptive options, preconception health, and reproductive wellness in our private consultation room.',
    priceEstimate: 'From KSh 200',
    duration: '15 mins',
    iconName: 'Users',
    category: 'Family Healthcare',
    available: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'srv-010',
    name: 'Rapid Diagnostic Tests (Malaria & Typhoid)',
    slug: 'rapid-diagnostic-tests',
    shortDescription: 'Fast, accurate RDT testing for Malaria (Pf/Pan) and Salmonella screening.',
    fullDescription: 'Get rapid, reliable point-of-care testing for fever causes like Malaria with results in 15 minutes, allowing immediate and targeted treatment according to Kenyan Ministry of Health guidelines.',
    priceEstimate: 'KSh 200 – KSh 350',
    duration: '15 mins',
    iconName: 'TestTube',
    category: 'Diagnostic Screening',
    available: true,
    featured: false,
    createdAt: new Date().toISOString(),
  },
];

export const initialArticles: HealthArticle[] = [
  {
    id: 'art-001',
    title: 'Managing High Blood Pressure: Essential Daily Practices for Kenyan Families',
    slug: 'managing-high-blood-pressure-kitale',
    excerpt: 'Hypertension is known as the "silent killer" because it rarely shows early symptoms. Discover practical diet, exercise, and medication adherence steps to keep your heart healthy.',
    content: `### Understanding Blood Pressure Numbers
Blood pressure measures the force of circulating blood against the walls of the arteries. A normal reading is typically around **120/80 mmHg**. When systolic pressure consistently reaches 140 mmHg or diastolic pressure reaches 90 mmHg, hypertension is diagnosed.

### Why Routine Screening Matters
Because elevated blood pressure develops gradually without obvious symptoms, regular monitoring is vital. At Gods Favor Pharmacy along Kijana Wamalwa Road in Kitale, we offer fast, calibrated blood pressure checks.

### Key Lifestyle Habits for Healthy Blood Pressure
1. **Reduce Sodium (Table Salt) Intake**: Replace excessive table salt and bouillon cubes with natural herbs and garlic.
2. **Increase Potassium-Rich Foods**: Incorporate fresh local bananas, traditional leafy greens (Sukuma Wiki, Managu, Terere), and avocados.
3. **Regular Physical Activity**: Aim for at least 30 minutes of brisk walking 5 days a week.
4. **Stress Management**: Prioritize restful sleep and manage daily stress.
5. **Never Stop Medication Abruptly**: If you are prescribed Amlodipine, Losartan, or Enalapril, take your dose consistently even when you feel completely fine.

*Have questions about your blood pressure readings? Call our clinical pharmacist directly at 07417758578.*`,
    category: 'Cardiovascular Health',
    author: 'Gods Favor Clinical Team',
    readTime: '4 min read',
    publishedDate: '2026-08-10',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80',
    tags: ['Blood Pressure', 'Hypertension', 'Diet', 'Heart Health'],
    published: true,
  },
  {
    id: 'art-002',
    title: 'Safe Antibiotic Use: Why You Must Always Complete Your Prescribed Course',
    slug: 'safe-antibiotic-usage-guidelines',
    excerpt: 'Stopping antibiotics early because you feel better is one of the main drivers of antimicrobial resistance. Learn how to take antibiotics safely and effectively.',
    content: `### The Science of Antibiotics
Antibiotics are powerful medications designed to kill or inhibit the growth of harmful bacteria. They are completely ineffective against viral infections such as the common cold, viral coughs, or influenza.

### The Danger of Incomplete Antibiotic Courses
When you begin an antibiotic treatment (such as Amoxicillin or Augmentin), the weakest bacteria die in the first 48 hours, which makes you feel significantly improved. However, the stronger, more resilient bacteria remain alive. 

If you stop taking the medicine at this stage:
- The surviving bacteria multiply rapidly.
- They mutate and develop resistance to that antibiotic.
- Subsequent infections become far more difficult and expensive to treat.

### Golden Rules for Antibiotic Safety:
- **Never self-medicate**: Always obtain a valid prescription following a professional health evaluation.
- **Take doses at evenly spaced intervals**: e.g., every 8 hours or 12 hours as instructed.
- **Never share leftover antibiotics** with friends or family members.
- **Ask your pharmacist about food interactions**: Some antibiotics should be taken with meals, while others require an empty stomach.`,
    category: 'Medication Safety',
    author: 'Pharm. Gods Favor Kitale',
    readTime: '5 min read',
    publishedDate: '2026-08-04',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&auto=format&fit=crop&q=80',
    tags: ['Antibiotics', 'Medication Safety', 'Health Education'],
    published: true,
  },
  {
    id: 'art-003',
    title: 'Preventing and Managing Infant Dehydration from Diarrhea: The ORS + Zinc Protocol',
    slug: 'infant-dehydration-ors-zinc-protocol',
    excerpt: 'Diarrhea is a leading health concern in young children. Learn the WHO-endorsed protocol of Oral Rehydration Salts and Zinc to protect your baby from severe dehydration.',
    content: `### Recognizing Dehydration in Babies
Young infants have small fluid reserves and can become dehydrated rapidly during bouts of watery diarrhea or vomiting.

**Warning signs of dehydration:**
- Dry mouth and sunken eyes.
- Depressed soft spot (fontanelle) on the baby's head.
- Crying without tears.
- Fewer wet diapers (no urination for over 6 hours).
- Unusual drowsiness, lethargy, or irritability.

### The Correct Way to Prepare ORS
1. Wash your hands thoroughly with clean water and soap.
2. Pour the entire contents of 1 ORS sachet into a clean container.
3. Measure exactly **500ml (or 1 liter depending on packet size)** of boiled, cooled drinking water.
4. Stir thoroughly until the powder completely dissolves.
5. Give small, frequent sips to the baby using a cup and spoon (not a feeding bottle).

### The Role of Zinc Supplements
Zinc given for 10 to 14 days reduces the severity and duration of diarrhea episodes and boosts intestinal mucosal immunity for up to 3 months.

*If the infant cannot keep fluids down or shows extreme lethargy, bring them to the pharmacy or hospital immediately.*`,
    category: 'Pediatric Health',
    author: 'Maternal & Child Health Unit',
    readTime: '4 min read',
    publishedDate: '2026-07-28',
    imageUrl: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=800&auto=format&fit=crop&q=80',
    tags: ['Pediatrics', 'Baby Care', 'ORS', 'First Aid'],
    published: true,
  },
  {
    id: 'art-004',
    title: 'Living Well with Type 2 Diabetes: Nutrition, Monitoring & Foot Care in Kitale',
    slug: 'living-well-type-2-diabetes-guide',
    excerpt: 'A comprehensive practical guide on balancing staple Kenyan carbohydrates, interpreting glucose test readings, and protecting your feet.',
    content: `### Balancing Local Kenyan Meals for Stable Glucose
Managing Type 2 diabetes does not mean eliminating all traditional foods. It is about smart portions and high-fiber choices.

- **Portion the Plate Method**: Half of the plate should consist of fresh non-starchy vegetables (Kales, Spinach, Cabbage, Traditional Greens), one quarter lean protein (beans, lentils, fish, lean beef), and one quarter complex carbohydrates (brown ugali, sweet potatoes, whole grain sorghum).
- **Avoid Refined Sugars**: Steer clear of sugar-sweetened sodas, packaged juices, and refined mandazis.

### Daily Blood Glucose Targets
For most adults with diabetes:
- **Fasting / Before meals**: 4.0 – 7.0 mmol/L (72 – 126 mg/dL)
- **2 hours after meals**: Under 8.5 mmol/L (153 mg/dL)

### Daily Diabetic Foot Care Checklist
1. Wash feet daily in lukewarm water with mild soap; dry gently, especially between the toes.
2. Inspect your feet daily for small cuts, blisters, redness, or cracks.
3. Never walk barefoot, even indoors.
4. Wear clean cotton socks and well-fitting footwear.

*Visit Gods Favor Pharmacy for test strips, glucose monitors, or a fast in-person blood sugar test.*`,
    category: 'Chronic Care',
    author: 'Gods Favor Clinical Team',
    readTime: '6 min read',
    publishedDate: '2026-07-15',
    imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=800&auto=format&fit=crop&q=80',
    tags: ['Diabetes', 'Nutrition', 'Blood Sugar', 'Chronic Care'],
    published: true,
  },
];
